package com.aerospike.timf.generators;

import java.util.Date;
import java.util.Random;
import java.util.UUID;
import java.util.concurrent.ThreadLocalRandom;
import java.util.concurrent.TimeUnit;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.aerospike.timf.model.Transaction;

@Service
public class TransactionGeneratorService {
    public final static String[] ITEMS = {
            "Air Fryer",
            "Armchair",
            "Aquarium",
            "Allspice",
            "Aluminum Foil",
            "Air Conditioner",
            "Atlas",
            "Aprons",
            "Address Book",
            "Air Mattress",
            "Armoire",
            "Alarm Clock",
            "Aspirin",
            "Antiperspirant",
            "Air freshener",
            "Alarm clock",
            "Ashtray",
            "Apron",
            "Artificial flowers",
            "Artwork",
            "Ashcan",
            "Attic ladder",
            "Awning",
            "Axe",
            "Automatic vacuum cleaner",
            "Apple corer",
            "Angle broom",
            "Ant killer",
            "Ant trap",
            "Aluminum foil",
            "Aerosol spray",
            "Auto floor mats",
            "Avocado slicer",
            "Auto wax",
            "Apple peeler",
            "Anchor",
            "Aluminum ladder",
            "Air conditioner",
            "Airtight containers",
            "Adjustable wrench",
            "Aquarium pump",
            "Audio system",
            "Alarm system",
            "Acid cleaner",
            "Apple cutter",
            "Acrylic paint",
            "Acrylic yarn",
            "Arm guard",
            "Ankle weights",
            "Activity tracker",
            "Binders",
            "Baskets",
            "Blow Dryer",
            "Bible",
            "Blu Rays",
            "Bulletin Board",
            "Bread Box",
            "Basketball",
            "Burglar Alarm",
            "Blankets",
            "Bed",
            "Boxers",
            "Batteries",
            "Belt",
            "Banjo",
            "Bug Spray",
            "Backdoor",
            "Blinds",
            "Baseball Bat",
            "Books",
            "Barometer",
            "Bicycle Pump",
            "Bag",
            "Bottle",
            "Blender",
            "Bread maker",
            "Bakeware",
            "Barbecue grill",
            "Bathroom scale",
            "Bath mat",
            "Bedding",
            "Bookcase",
            "Bottle opener",
            "Bread bin",
            "Broom",
            "Bucket",
            "Blender bottle",
            "Bottle brush",
            "Bread knife",
            "Bamboo cutting board",
            "Butcher knife",
            "Bar stool",
            "Beer mug",
            "Bedspread",
            "Ballpoint pen",
            "Bathrobe",
            "Backpack",
            "Baby gate",
            "Beach umbrella",
            "Bean bag chair",
            "Birdhouse",
            "Blanket",
            "Blind",
            "Bluetooth speaker",
            "Body pillow",
            "Bookends",
            "Booster seat",
            "Bulletin board",
            "Butterfly net",
            "Bag sealer",
            "Baking dish",
            "Bar soap",
            "Bassinet",
            "Bath towel",
            "Containers",
            "Cell Phone",
            "Crayons",
            "Camera",
            "Cans Of Soup",
            "Cookie Cutter",
            "Coffee Table",
            "Ceiling Fan",
            "Coupons",
            "Colors",
            "Curtain",
            "Cards",
            "Cat Litter",
            "Cotton Balls",
            "Cereal",
            "Card Table",
            "Chairs",
            "Car Keys",
            "Copier",
            "Clothes",
            "Clothes Washer",
            "Cough Drops",
            "Coffee Maker",
            "Cleaner",
            "Coffee maker",
            "Curtains",
            "Chair",
            "Couch",
            "Candles",
            "Cutting board",
            "Can opener",
            "Chandelier",
            "Clock",
            "Carpet",
            "Comforter",
            "Coasters",
            "Computer",
            "Crib",
            "Coffee table",
            "Cabinet",
            "Cleaning products",
            "Coat hanger",
            "Chimney brush",
            "Chopping knife",
            "Cheese grater",
            "Chalkboard",
            "Cell phone charger",
            "Charger plates",
            "Chinese lantern",
            "Chip and dip set",
            "Clothes hanger",
            "Clothes iron",
            "Coffee mug",
            "Colander",
            "Comfort grip scissors",
            "Compact mirror",
            "Computer mouse",
            "Cookie sheet",
            "Copper cookware",
            "Corn broom",
            "Corner desk",
            "Crockpot",
            "Crystal vase",
            "Duvet",
            "Dish Rag",
            "Door Knob",
            "Door Stop",
            "Duster",
            "Dinner Set",
            "Dust Pan",
            "Digger",
            "Dish Towel",
            "Drape",
            "Deep Bathtub",
            "Drill Dryer",
            "Dish Washer",
            "Dressers",
            "Dishwasher",
            "Dining table",
            "Dresser",
            "Dryer",
            "Doormat",
            "Dustpan",
            "Dehumidifier",
            "Drying rack",
            "Desk",
            "Duvet cover",
            "Dutch oven",
            "Drip coffee maker",
            "Dinnerware set",
            "Dog bed",
            "Digital scale",
            "Down pillow",
            "Drain snake",
            "Drinking glasses",
            "Dog collar",
            "Drum set",
            "Dust mop",
            "Disposable gloves",
            "Drawer organizer",
            "Dumbbells",
            "Desk lamp",
            "Decorative pillows",
            "Dish soap",
            "Drink coasters",
            "Door stopper",
            "Dog leash",
            "Dry erase board",
            "Deep fryer",
            "Drinking straws",
            "Digital camera",
            "Double boiler",
            "Dartboard",
            "Digital thermometer",
            "Dust mask",
            "Doorbell",
            "Extension Cord",
            "Electric Guitar",
            "End Tables",
            "Edger",
            "Electric Fan",
            "Eraser",
            "Electric Toothbrush",
            "Earplugs",
            "Electric Razor",
            "Eye Drops",
            "Egg Cup",
            "Envelopes",
            "Ethernet Cable",
            "Espresso Maker",
            "Egg Timer",
            "Egg Holder",
            "Egg Cooker",
            "Electric kettle",
            "Espresso machine",
            "Extension cord",
            "Egg slicer",
            "Electric can opener",
            "Egg poacher",
            "Electric griddle",
            "Electric blanket",
            "Electric fry pan",
            "Exercise bike",
            "Electric mixer",
            "Envelope opener",
            "Electric toothbrush",
            "Egg timer",
            "Ear plugs",
            "Extension ladder",
            "Electric shaver",
            "Electric razor",
            "Exercise ball",
            "Electric stapler",
            "Eye mask",
            "Essential oil diffuser",
            "Embroidery hoop",
            "Exercise mat",
            "Electric fan",
            "Elastic bands",
            "Egg cooker",
            "Earphones",
            "Electric hot pot",
            "Exercise bench",
            "Electric air pump",
            "Egg beater",
            "Electric pressure cooker",
            "Electric skillet",
            "Eye dropper",
            "Electric fondue pot",
            "Foot Stool",
            "Fireplace",
            "Furnace",
            "Frying Pan",
            "Fish",
            "Flatscreen Tv",
            "Foam",
            "Fax Machine",
            "Figurine",
            "Floss",
            "Fly Swatter",
            "Fire Extinguisher",
            "Fish Flakes",
            "Fly",
            "Flashlight",
            "Food Processor",
            "Freezer",
            "Fan",
            "Food processor",
            "Fireplace screen",
            "Flatware",
            "Food storage containers",
            "French press",
            "Fire extinguisher",
            "Frying pan",
            "Floor lamp",
            "Fly swatter",
            "Feather duster",
            "Fabric softener",
            "Flour sifter",
            "Firewood rack",
            "First aid kit",
            "Foam roller",
            "Fishing rod",
            "Feather pillow",
            "Food dehydrator",
            "Film camera",
            "Foot massager",
            "Faucet aerator",
            "Felt pads",
            "Fire starter",
            "Flannel sheets",
            "Flare gun",
            "Food chopper",
            "Foil cutter",
            "Fruit bowl",
            "File organizer",
            "Flute",
            "Fingerless gloves",
            "Foldable chair",
            "Fire pit",
            "Filter pitcher",
            "Fondue forks",
            "Face mask",
            "Felt tip pens",
            "Garden Rake",
            "Groceries",
            "Garment",
            "Glass",
            "Gum",
            "Gate",
            "Gravy",
            "Garlic",
            "Garbage",
            "Globe",
            "Grass",
            "Grain",
            "Glass Cups",
            "Gym",
            "Gps",
            "Glasses",
            "Gear",
            "Green Bin",
            "Garbage can",
            "Grill",
            "Glassware",
            "Garden hose",
            "Grater",
            "Gas stove",
            "Gloves",
            "Glass vase",
            "Glue gun",
            "Grill brush",
            "Glass cleaner",
            "Garment steamer",
            "Garden tools",
            "Gift wrap",
            "Garlic press",
            "Glass baking dish",
            "Grapefruit knife",
            "Gummy bear mold",
            "Guest book",
            "Game controller",
            "Glass pitcher",
            "Grooming kit",
            "Glass coffee mug",
            "Ginger grater",
            "Gravy boat",
            "Glass storage jars",
            "Glass bottle",
            "Gel pens",
            "Gold flatware",
            "Glass measuring cup",
            "Garden sprayer",
            "Glass cutting board",
            "Gel seat cushion",
            "Hammer",
            "Hook",
            "Hinge",
            "Hand Mixer",
            "Hearth",
            "Hanger",
            "Hand Sanitizer",
            "Hose",
            "Hamper",
            "Hurricane Lamp",
            "Highlighter",
            "Hutch",
            "Hall Runner",
            "Houseplant",
            "Hooks",
            "Hat Rack",
            "Hair Dryer",
            "Humidifier",
            "Hair dryer",
            "Heater",
            "Hammock",
            "Handheld vacuum",
            "Hand soap dispenser",
            "Headphones",
            "Houseplants",
            "Hangers",
            "Hiking boots",
            "Hand mixer",
            "Herb grinder",
            "High chair",
            "Handheld steamer",
            "Hose reel",
            "Hairbrush",
            "Handheld mirror",
            "Heating pad",
            "Hand sanitizer",
            "Hand truck",
            "Hat rack",
            "Hurricane lamp",
            "Honey pot",
            "Hamburger press",
            "Herb scissors",
            "Hair curler",
            "Home security system",
            "Hair straightener",
            "Hummus maker",
            "Handheld blender",
            "Hiking poles",
            "House slippers",
            "Hula hoop",
            "Handheld sewing machine",
            "Handheld mixer",
            "Heart rate monitor",
            "Handheld microscope",
            "Hair clipper",
            "Hiking backpack",
            "Hot Plate",
            "Ink Pen",
            "Icemaker",
            "Ivory Soap",
            "Inch Ruler",
            "Ironing Board",
            "Ice Cream Maker",
            "Ice Cream",
            "Insect",
            "Invisible",
            "Ironing board",
            "Ice cube tray",
            "Incense holder",
            "Insulated water bottle",
            "Instant pot",
            "Insect repellent",
            "Iron",
            "Ice cream scoop",
            "Inflatable pool",
            "Indoor grill",
            "Intercom system",
            "Immersion blender",
            "Induction cooktop",
            "Interlocking storage bins",
            "Inflatable mattress",
            "Ice cream maker",
            "Insect zapper",
            "Insulated lunch bag",
            "Infrared thermometer",
            "Inflatable sofa",
            "Inflatable kayak",
            "Ice cream container",
            "Insulated grocery bag",
            "Interdental brush",
            "Instant camera",
            "Incense cones",
            "Insulated travel mug",
            "Indoor plant",
            "Insulated picnic basket",
            "Iced tea pitcher",
            "Ironing board cover",
            "Infrared heater",
            "Inflatable punching bag",
            "Insulated wine glass",
            "Insect screen door",
            "Inflatable pool float",
            "Insulated food jar",
            "Inflatable globe",
            "Jar",
            "Junk Drawer",
            "Jammies",
            "Juice",
            "Jackhammer",
            "Juniper",
            "Jumper",
            "Japanese Child",
            "Jacket Jeans",
            "Jewelry Box",
            "Jump Rope",
            "Jerseys",
            "Jay Cloth",
            "Jam",
            "Jewelry",
            "Juicer",
            "Jar opener",
            "Jigsaw puzzle",
            "Jewelry box",
            "Jute rug",
            "Jumper cables",
            "Juice dispenser",
            "Japanese teapot",
            "Jingle bells",
            "Jute basket",
            "Jumbo laundry bag",
            "Junior bed",
            "Jetted bathtub",
            "Jumbo storage bag",
            "Jacquard tablecloth",
            "Jute placemats",
            "Jazz poster",
            "Jalousie window",
            "Jar labels",
            "Jigsaw puzzle mat",
            "Jumbo baking sheet",
            "Jump rope",
            "Jetted showerhead",
            "Japanese tea set",
            "Jute runner",
            "Jumbo pencil sharpener",
            "Jelly roll pan",
            "Jute rope",
            "Jewelry armoire",
            "Juice extractor",
            "Jet lighter",
            "Jumbo crayons",
            "Jute coasters",
            "Jumbo mug",
            "Jar funnel",
            "Japanese knife",
            "Jumbo binder clip",
            "Jockey hat rack",
            "Jumper dress",
            "Junk",
            "Key",
            "Keyboard",
            "Keyboard Pad",
            "Kerosene Heater",
            "Ketchup",
            "Kitchen Appliances",
            "Kittens",
            "Knives",
            "Knot",
            "Kettle",
            "Knife block",
            "Kitchen scale",
            "Key holder",
            "Ketchup dispenser",
            "Kneading board",
            "Keyboard tray",
            "Kitchen trolley",
            "Kerosene heater",
            "Kitchen timer",
            "Kneading machine",
            "Kitchen mat",
            "Kebab skewers",
            "Kevlar gloves",
            "Kitchen backsplash",
            "Kitten food",
            "Kinetic sculpture",
            "Koi pond",
            "Karaoke machine",
            "Kite",
            "Keyboard cover",
            "Key box",
            "Kitchen brush",
            "Knit throw",
            "Knife sharpener",
            "Kitchen fan",
            "Kitchen faucet",
            "Kissing ball",
            "Kitchen apron",
            "Kettlebell",
            "Knitted dishcloth",
            "Kitchen shears",
            "Kitchen scissors",
            "Knife magnet",
            "Keffiyeh scarf",
            "Light Bulbs",
            "Light Switch",
            "Lingerie",
            "Laminate",
            "Litter Box",
            "Lemon",
            "Light",
            "Leaf Blower",
            "Litterbox",
            "Loofa",
            "Lint Brush",
            "Linens",
            "Liquid Soap",
            "Lid",
            "Lysol Spray",
            "Lamp",
            "Ladder",
            "Laundry basket",
            "Lazy Susan",
            "Lemon squeezer",
            "Letter opener",
            "Light bulb",
            "Light switch",
            "Linen closet",
            "Lock",
            "Loofah",
            "Lotion dispenser",
            "Lounger",
            "Lunch box",
            "Ladle",
            "Leather cleaner",
            "Lemon zester",
            "Level",
            "Lint brush",
            "Lip balm",
            "Liquid soap dispenser",
            "Listening device",
            "Lockbox",
            "Love seat",
            "Luggage",
            "Lunch container",
            "Lunch tray",
            "Lunchbox cooler",
            "Lusterware",
            "Lampshade",
            "Landline phone",
            "Laptop desk",
            "Laundry detergent",
            "Lawn chair",
            "Leaf blower",
            "LED light",
            "Leg rest",
            "Lemon press",
            "Lens cleaner",
            "Money Box",
            "Medicines",
            "Magnets",
            "Mothballs",
            "Mustard",
            "Mittens",
            "Mattress Pads",
            "Measuring Cups",
            "Martini Glasses",
            "Margerine",
            "Muffin Tin",
            "Mousetrap",
            "Mugs",
            "Monopoly Game",
            "Medicine",
            "Makeup",
            "Mixing Spoons",
            "Memo Pads",
            "Markers",
            "Mattress",
            "Microwave",
            "Mixer",
            "Mop",
            "Mirror",
            "Magazine rack",
            "Measuring cup",
            "Meat grinder",
            "Medicine cabinet",
            "Memo board",
            "Menu board",
            "Mesh strainer",
            "Microwave stand",
            "Mini fridge",
            "Miniature clock",
            "Mirror frame",
            "Mixing bowl",
            "Moisturizer",
            "Money clip",
            "Monitor",
            "Mortar and pestle",
            "Muffin tin",
            "Mug",
            "Multipurpose cleaner",
            "Music player",
            "Mustard pot",
            "Makeup brush",
            "Martini shaker",
            "Massage chair",
            "Massage oil",
            "Mattress pad",
            "Meat thermometer",
            "Melon baller",
            "Memory foam pillow",
            "Menorah",
            "Microfiber cloth",
            "Microwave plate cover",
            "Milk jug",
            "Novels",
            "Napkins",
            "Nut Cracker",
            "Nose Trimmer",
            "News Paper",
            "Nylon String",
            "Necklace",
            "Nails",
            "Noodles",
            "Note Paper",
            "Napkin holder",
            "Nightstand",
            "Noodle maker",
            "Napkin ring",
            "Nutcracker",
            "Nutmeg grinder",
            "Napkin dispenser",
            "Neck pillow",
            "Nail clippers",
            "Night light",
            "Nose hair trimmer",
            "Notebook",
            "Numbing cream",
            "Nose spray",
            "Nose wipes",
            "Notepad",
            "Nut bowl",
            "Nut chopper",
            "Nut driver",
            "Nail brush",
            "Nail file",
            "Neck massager",
            "Necktie rack",
            "Neon sign",
            "Nesting bowls",
            "Newel post",
            "Newspaper rack",
            "Night cream",
            "Noodle bowl",
            "Nose plugs",
            "Nursing pillow",
            "Nylon scrubber",
            "Nectar collector",
            "Napping blanket",
            "Open Door",
            "Oats",
            "Oven",
            "Oval Table",
            "Orange Juicer",
            "Oven Cleaner",
            "Oreos",
            "Oil",
            "Object",
            "Oven Mitts",
            "Oven mitts",
            "Oil dispenser",
            "Organizer rack",
            "Outdoor broom",
            "Oven cleaner",
            "Outlet covers",
            "Onion chopper",
            "Orange juicer",
            "Oil diffuser",
            "Oval platter",
            "Office chair",
            "Outdoor rug",
            "Outdoor string lights",
            "Overbed table",
            "Oval mirror",
            "Oxygen machine",
            "Oscillating fan",
            "Orange peeler",
            "Outdoor thermometer",
            "Oil lamp",
            "Outdoor plant stand",
            "Oreck vacuum cleaner",
            "Oil brush",
            "Oven thermometer",
            "Outlet surge protector",
            "Oak cutting board",
            "Oil pourer",
            "Organic waste bin",
            "Oil and vinegar dispenser",
            "Outdoor fire pit",
            "Ornament storage box",
            "Oilcloth tablecloth",
            "Onion keeper",
            "Popcorn Maker",
            "Pressure Fryer",
            "Pressure Cooker",
            "Plastic Plates",
            "Pliers",
            "Patio Heater",
            "Polo Shirt",
            "Picture Frame",
            "Posters",
            "Perfume",
            "Plates",
            "Parka",
            "Putty Knife",
            "Phones",
            "Pencils",
            "Plums",
            "Penny Loafers",
            "Poncho",
            "Pants",
            "Printer",
            "Poker",
            "Pillowcase",
            "Pots and pans",
            "Picture frame",
            "Paper towel holder",
            "Pressure cooker",
            "Pest control spray",
            "Paintbrush",
            "Power strip",
            "Pitcher",
            "Placemats",
            "Pot holder",
            "Pepper grinder",
            "Potato masher",
            "Personal fan",
            "Patio furniture",
            "Pasta maker",
            "Pillar candles",
            "Pet food container",
            "Pin board",
            "Popcorn maker",
            "Propane tank",
            "Portable vacuum cleaner",
            "Photo album",
            "Pizza cutter",
            "Potting soil",
            "Pastry brush",
            "Pill organizer",
            "Plastic wrap",
            "Portable air conditioner",
            "Pillar candle holder",
            "Pressure washer",
            "Paper shredder",
            "Pasta strainer",
            "Pillar candle set",
            "Paper clips",
            "Playpen",
            "Paint roller",
            "Pedestal fan",
            "Pie dish",
            "Pint glasses",
            "Query",
            "Quaker Oats",
            "Quest",
            "Queen",
            "Quarry",
            "Quarter",
            "Quiche",
            "Quilt",
            "Quilt Cover",
            "Quill",
            "Quartz Countertop",
            "Quiche Dish",
            "Quesadilla Maker",
            "Quilting Hoop",
            "Quick Dry Towels",
            "Quinoa Bowl",
            "Quilted Bedspread",
            "Quicksilver Polish",
            "Quilted Jacket",
            "Queen Size Bed",
            "Quail Egg Holder",
            "Quad Chair",
            "Queso Dip Bowl",
            "Quiche Pan",
            "Quality Knives",
            "Quiet Fan",
            "Quilt Rack",
            "Quilted Table Runner",
            "Quartz Wall Clock",
            "Quickie Mop",
            "Quail Feather Duster",
            "Quiche Lorraine Pan",
            "Quill Pen",
            "Quick Release Skewers",
            "Quaker Oats Container",
            "Quilt Hanger",
            "Quicksilver Candlesticks",
            "Quilted Sofa Cover",
            "Quinoa Container",
            "Quick Fix Sewing Kit",
            "Quilted Storage Box",
            "Quilted Pillow Covers",
            "Quilted Oven Mitts",
            "Quilted Placemats",
            "Quail Shaped Cutting Board",
            "Quick Drying Bath Mat",
            "Rouge",
            "Rattle",
            "Radio",
            "Radiator",
            "Rabbit",
            "Rifle",
            "Rags",
            "Rugs",
            "Rock Salt",
            "Ribbon",
            "Range",
            "Runner",
            "Revolver",
            "Ring",
            "Rice Cooker",
            "Refrigerator",
            "Roasting Pan",
            "Rubber Gloves",
            "Rolling Pin",
            "Rice Storage Container",
            "Remote Control Holder",
            "Red Wine Glass",
            "Reading Lamp",
            "Rice Dispenser",
            "Rubber Bands",
            "Rustic Coffee Table",
            "Roomba Vacuum Cleaner",
            "Router",
            "Raincoat",
            "Radiator Heater",
            "Roasting Rack",
            "Room Divider Screen",
            "Rotisserie Oven",
            "Recliner Chair",
            "Retro Phone",
            "Record Player",
            "Robot Lawn Mower",
            "Rattan Basket",
            "Reusable Grocery Bags",
            "Rice Paddle",
            "Rain Showerhead",
            "Ravioli Maker",
            "Round Tablecloth",
            "Rope Basket",
            "Rustic Chandelier",
            "Rolling Laundry Cart",
            "Router Bit Set",
            "Rubber Duck",
            "Roasting Skewers",
            "Rustic Wall Shelf",
            "Ratchet Screwdriver",
            "Ruffle Shower Curtain",
            "Running Belt",
            "Rustic Photo Frame",
            "Safe",
            "Saucer",
            "Scarf",
            "Screw Driver",
            "Settee",
            "Shades",
            "Sheet",
            "Sneakers",
            "Socks",
            "Spare Keys",
            "Spoon",
            "Spoons",
            "Stamps",
            "Stapler",
            "Stereo",
            "Sofa",
            "Stove",
            "Showerhead",
            "Stainless Steel Cutlery Set",
            "Salad Spinner",
            "Shower Curtain",
            "Slow Cooker",
            "Storage Ottoman",
            "Spice Rack",
            "Soap Dispenser",
            "Sandwich Maker",
            "Shoe Rack",
            "Side Table",
            "Steamer",
            "Stand Mixer",
            "Scented Candle",
            "Salad Bowl",
            "Storage Baskets",
            "Steam Iron",
            "Shower Caddy",
            "Soup Ladle",
            "Silk Pillowcase",
            "Soda Maker",
            "Shower Mat",
            "Serving Tray",
            "Salt and Pepper Shakers",
            "Storage Cabinet",
            "Salad Forks",
            "Swivel Chair",
            "Serving Spoons",
            "Strainer",
            "Sippy Cups",
            "Shoe Polisher",
            "Small Trash Can",
            "Stair Treads",
            "Saucepan",
            "Sofa Bed",
            "Springform",
            "Tapestry",
            "Teaspoon",
            "Telephone",
            "Thong",
            "Throws",
            "Timers",
            "Tissues",
            "Toaster Oven",
            "Toilet Brush",
            "Toilet Cleaner",
            "Tools",
            "Toothpaste",
            "Torch",
            "Towel",
            "Trash",
            "Trumpet",
            "Toaster",
            "Trash can",
            "Tea kettle",
            "Towels",
            "Toilet brush",
            "Tablecloth",
            "Tupperware",
            "Trivet",
            "Thermometer",
            "Tea set",
            "Toothbrush holder",
            "Tea infuser",
            "Timer",
            "Tissue box",
            "Tray",
            "Teapot",
            "Toothpaste dispenser",
            "Tortilla press",
            "Turkey baster",
            "Tongs",
            "Table runner",
            "Travel mug",
            "Tea strainer",
            "Tea towels",
            "Tile cleaner",
            "Tomato slicer",
            "Tape measure",
            "Tea light candles",
            "Tea bag organizer",
            "Tamale steamer",
            "Tank top hanger",
            "Tool kit",
            "Tea bag squeezer",
            "Tennis racket",
            "Tackle box",
            "Terrarium",
            "Travel iron",
            "Toy chest",
            "Tea tree oil",
            "Ugg boots",
            "Undershirt",
            "Underwear",
            "Umberella",
            "Umrella",
            "Utensils",
            "Underwear Drawer",
            "Understanding",
            "Uniform",
            "Umbrella",
            "Utensil holder",
            "Utility knife",
            "Upright vacuum",
            "Ultrasonic humidifier",
            "USB fan",
            "Universal remote control",
            "Utility sink",
            "Urn",
            "Urinal",
            "Upholstery cleaner",
            "Utility cart",
            "Unbreakable dishes",
            "Unpaper towels",
            "USB charger",
            "Utility gloves",
            "Universal phone charger",
            "Utensil organizer",
            "UV light sanitizer",
            "Unplugged game",
            "Unbreakable cups",
            "Utility scissors",
            "Upholstery fabric",
            "Urine remover",
            "Utility ladder",
            "Utility hook",
            "Universal adapter",
            "Upholstery brush",
            "Utility tray",
            "Universal lid",
            "Vacuum",
            "Vaporizer",
            "Vault",
            "Vcr",
            "Vent",
            "Vicks",
            "Vitamins",
            "Vacuum cleaner",
            "Vegetable peeler",
            "Vase",
            "Vegetable steamer",
            "Vegetable chopper",
            "Vanity mirror",
            "Velcro strips",
            "Vacuum storage bags",
            "Vegetable spiralizer",
            "Vegetable grater",
            "Vegetable brush",
            "Vegetable slicer",
            "Vinyl tablecloth",
            "Vacuum sealer",
            "Vinegar bottle",
            "Vegetable basket",
            "Votive candle holder",
            "Vegetable colander",
            "Vegetable corer",
            "Vegetable dicer",
            "Wall",
            "Wardrobe",
            "Washcloth",
            "Washer",
            "Washing Machine",
            "Watch",
            "Water Heater",
            "Wood",
            "Wrench",
            "Washing machine",
            "Wine glasses",
            "Window cleaner",
            "Wall clock",
            "Whisk",
            "Waffle maker",
            "Water pitcher",
            "Wine rack",
            "Wine opener",
            "Wall art",
            "Water filter",
            "Wok",
            "Wardrobe hangers",
            "Wall shelf",
            "Wooden spoon",
            "Wireless charger",
            "Wind chimes",
            "Whistle kettle",
            "Waste bin",
            "X box",
            "Xeres",
            "Xbox",
            "Xylophone",
            "Xacto knife",
            "Xylene",
            "Xanthan gum",
            "Xenon lamp",
            "Yam",
            "Yard Stick",
            "Yoghurt",
            "Yogurt",
            "Youngsters",
            "Yoyo",
            "Yules",
            "Yoga mat",
            "Yellow cleaning gloves",
            "Yankee candle",
            "Yarn",
            "Yardstick",
            "Yam masher",
            "Yoga block",
            "Yoghurt maker",
            "Yellow duster",
            "Yoga ball",
            "Yakitori grill",
            "Yarn winder",
            "Yellow cloth napkins",
            "Yellow vase",
            "Yixing teapot",
            "Yellow dish brush",
            "Yacht model",
            "Zen garden",
            "Zeppelin",
            "Zero",
            "Zest",
            "Zest Soap",
            "Zinc",
            "Zipper",
            "Zither",
            "Zodiac",
            "Zigzag scissors",
            "Zen garden kit",
            "Zester",
            "Zucchini spiralizer",
            "Ziplock bags",
            "Zebra print curtains",
            "Zamboni ice scraper",
            "Zabuton meditation cushion",
            "Zircon stud finder",
            "Zippered mattress protector",
            "Zinc alloy bottle opener",
            "Zest soap dispenser",
            "Zebra wood cutting board",
            "Zenith shower caddy",
            "Zigzag bookshelf",
            "Zest grater",
            "Zoot suit hanger",
            "Zest scented candle",
    };
    public static final long DAYS_TO_GENERATE = 30;
    private static final long MILLISECONDS_IN_GENERATED_DAYS = TimeUnit.DAYS.toMillis(DAYS_TO_GENERATE); 
    @Autowired
    private NameGeneratorService nameGeneratorService;
    
    public Transaction generateTransaction(long id, String forPan, boolean inThePast) {
        Random random = ThreadLocalRandom.current();
        Transaction result = new Transaction();
        result.setAmount(random.nextInt(2500_00));
        result.setCustId("cust-"+random.nextInt(10_000_000));
        result.setDescription(ITEMS[random.nextInt(ITEMS.length)]);
        result.setMerchantName(nameGeneratorService.getName()+"'s Store");
        result.setPan(forPan);
        result.setTerminalId("Terminal-" + random.nextInt(20_000_000));
        Date now = new Date();
        result.setTxnDate(inThePast? new Date(now.getTime() - random.nextLong(MILLISECONDS_IN_GENERATED_DAYS)) : now);
        result.setTxnId(UUID.randomUUID().toString());
        return result;
    }
}
